# Generated by Django 3.0.5 on 2020-06-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200616_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='media/陈奕迅.png', upload_to='media'),
        ),
    ]
