# Generated by Django 3.0.5 on 2020-06-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200629_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='media/default.png', upload_to='media'),
        ),
    ]
