# Generated by Django 3.0.5 on 2020-07-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_collect'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user_collect',
            field=models.ManyToManyField(related_name='user_collected', to='app.User'),
        ),
    ]
