# Generated by Django 3.0.5 on 2020-07-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_user_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='collect_nums',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏数'),
        ),
    ]
