# Generated by Django 3.0.5 on 2020-07-07 15:25

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_collect'),
        ('blog', '0003_article_collect_nums'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={},
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.ArticleComment'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replyers', to='app.User'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='articlecomment',
            table=None,
        ),
    ]
